---
name: Update Edge App

on:
  push:
    branches:
      - main
      - feat/refactor-update-edge-app-workflow
    tags:
      - 'v*'

run-name: Updating RSS Reader in ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'stage' }}

jobs:
  deploy-stage:
    name: Updating RSS Reader in stage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: stage
    steps:
      - uses: actions/checkout@v4
      - uses: Screenly/edge-apps-actions/update@add-update-action
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_TEST }}
          environment: stage

  deploy-production:
    name: Updating RSS Reader in production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feat/refactor-update-edge-app-workflow'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: Screenly/edge-apps-actions/update@add-update-action
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_TEST }}
          environment: production
